import React from "react";
import LegalLayout from "./LegalLayout";

const Disclaimer = () => {
  return (
    <LegalLayout>
      <div className="space-y-6">
        <div>
          <h2 className="text-2xl font-black text-[#081028] tracking-tight">Disclaimer</h2>
          <p className="text-xs text-gray-400 font-semibold mt-1">Last Updated: May 2026</p>
        </div>

        <p className="text-sm text-gray-600 leading-relaxed">
          The information and output generated by Lumora.ai are provided on an "as is" basis without warranty of any kind.
        </p>

        <div className="h-px bg-gray-100" />

        <div className="space-y-3">
          <h3 className="text-base font-bold text-[#081028]">1. AI Output Limitations</h3>
          <p className="text-xs text-gray-600 leading-relaxed">
            Lumora.ai uses state-of-the-art machine learning models to synthesize visuals. AI-generated images do not always reflect real-world facts or design principles and can occasionally contain anomalies or distorted structures. We are not responsible for the thematic accuracy, contextual factualness, or moral interpretations of generated media.
          </p>
        </div>

        <div className="space-y-3">
          <h3 className="text-base font-bold text-[#081028]">2. No Professional Advice</h3>
          <p className="text-xs text-gray-600 leading-relaxed">
            The outputs produced by our models (such as architectural concepts, character designs, UI concepts) are purely for visualization and brainstorming assistance. They do not constitute professional engineering, architectural, or copyright-cleared product advice. You are responsible for consulting certified human specialists before utilizing designs for physical constructions or industrial manufacturing.
          </p>
        </div>

        <div className="space-y-3">
          <h3 className="text-base font-bold text-[#081028]">3. Third Party Copyrights</h3>
          <p className="text-xs text-gray-600 leading-relaxed">
            While our models are trained on large public datasets, AI generated outputs can occasionally resemble copyrighted human illustrations. It is the user's responsibility to verify that their generated images do not infringe upon existing third-party trademarks or proprietary characters prior to large scale commercial runs.
          </p>
        </div>

        <div className="space-y-3">
          <h3 className="text-base font-bold text-[#081028]">4. Contact Disclaimer Support</h3>
          <p className="text-xs text-gray-600 leading-relaxed">
            If you believe an output generated on our platform violates your copyright, please report the generation to:
          </p>
          <p className="text-xs font-bold text-green-600 mt-2 bg-green-50/50 border border-green-100 inline-block px-3 py-1.5 rounded-lg">
            legal@lumora.ai
          </p>
        </div>
      </div>
    </LegalLayout>
  );
};

export default Disclaimer;
